### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by HimAtcoding**

### CODE REVIEW

**Comment by GitHubEmploy** [comment]
image

Please do not compile, it adds the .ctxts as well, the only files that should be added or modified are YourName.java, the Classroom.java and your picture and sound

**Comment by HimAtcoding** [comment]
what do i do to help

**Comment by GitHubEmploy** [comment]
delete the .ctxt files

**Comment by GitHubEmploy** [comment]
and .class files

**Pull request closed without merging**
