### PR TITLE
Nikhil Prabhu - Finished code, ready to merge

### PR DESCRIPTION
**Pull request by Trolleroof**
image

Mohit moment

### CODE REVIEW

**Comment by Trolleroof** [comment]
deleted kilgore rip

**Review by GitHubEmploy — CHANGES_REQUESTED** [review]
Add back the kilgore trout file

**Comment by Trolleroof** [comment]
kilgore is back

**Review by GitHubEmploy — APPROVED** [review]
nice

**Comment by GitHubEmploy** [comment]
delete your .DS_Store files, and why is KilgoreTrout modified? please re read the directions

**Comment by Trolleroof** [comment]
it doesnt say that in the directions anywhere but sure 

also the reason it says that kilgore was changed is because I deleted it and I asked you if i should bring it back, and you said yes, so i did

**Comment by GitHubEmploy** [comment]
スクリーンショット 2023-08-30 午前11 48 37
 yea they cause issues, im going to delete the .ds files

**Comment by GitHubEmploy** [comment]
ok good job

**Pull request merged**
